version: "3.1"

services:
  db:
    image: mysql:8.0.31
    ports:
      - 13306:3306
    volumes:
      - ${HOME}/workspace/docker-apps/mysql-8.0.31/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  adminer:
    image: adminer:4.8.1
    ports:
      - 8088:8080