basePath: /api/v1
host: 127.0.0.1:8080
info:
  contact: {}
  version: "1.0"
paths:
  /posts2:
    get:
      consumes:
      - application/json
      description: 可按时间或分数排序查询帖子列表
      parameters:
      - description: Bearer JWT
        in: header
        name: Authorization
        required: true
        type: string
      - in: query
        name: order
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      responses: {}
      summary: 升级版帖子列表接口
swagger: "2.0"
